### ISSUE TITLE
Add Post viewing and editing from django admin

### ISSUE THREAD

**Issue by failedreality** [regularstuff/tildeblog#16]
Need to enable the view to see the posts in the django admin.
that way all admins have access to see the posts, edit or even delete if needed.

**Comment by readytheory** [comment]
I think this is also covered by issue 22 that Steve will merge in.  On the render site I gave roles to admins.  Let me know if I am missing the point though

**Comment by failedreality** [comment]
This wont cover it unless you are adding in a section on the urls.py to tie it all together.  At least thats the way it is on another django site im working on.

**Comment by readytheory** [comment]
Thanks.  I don't know what is normal usage of admin.  I do know django's admin panel comes with "Staff" by default.  Are you suggesting we should create an endpoint that let's "staff" (or some role we define) easily view/edit posts?

**Comment by failedreality** [comment]
Let me get this working and I wil show you and then we can move forward on next steps after that

**Comment by failedreality** [comment]
At the same time I am adding this I will also make a change to the model (which will **NOT** require a migration)
so that all objects that are stored will show the specific title (for posts) and name (for tags) instead of a generic object(01)

I have the concept working and will finalize and request a pull for review.

**Comment by regularstuff** [comment]
changes merged

**Comment by failedreality** [comment]
I think we can close this out now the merge has been completed.
