### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by regularstuff** [regularstuff/tildeblog#17]
Steve168 has a good candidate favicon.  It hasattribution requirements.  This is to implement the "bindle" icon he found as a favicon.

**Comment by SteveJFraser** [comment]
I copied the attribute link when i got the favicon and attributed it on Facebook and X so I think it should be ok to use it, unless you want to redo it for peace of mind

**Comment by readytheory** [comment]
I am going to use another icon from flaticons and put attribute it to  <a href="https://www.flaticon.com/free-icons/refugee" title="refugee icons">Refugee icons created by Freepik - Flaticon</a>
