### ISSUE TITLE
Create Response/Return page after submission

### ISSUE THREAD

**Issue by failedreality** [regularstuff/tildeblog#5]
Need to create a response/submitted return once someone posts an entry, I believe right now its just a blank HTML response page.

**Comment by failedreality** [comment]
After looking over the code the result was the following:
In til/views.py
After the POST I changed the return to the following:
return HttpResponseRedirect("")
to 
return render(request, 'til/post_thanks.html')

Then I created a very simple HTML called post_thanks.html under the til/templates/til
post_thanks.html

Tested this 6 times making posts and all is working.

Form:
![image](https://github.com/regularstuff/tildeblog/assets/933095/0586187b-7652-499a-93ae-9762e0358e7b)

Response:
![image](https://github.com/regularstuff/tildeblog/assets/933095/80e16389-e4ab-4617-95aa-6cd2762fffff)

**Comment by failedreality** [comment]
This is under feature-0.0.2 branch
@readytheory @SteveJFraser @

**Comment by regularstuff** [comment]
This was merged and am closing the issue
