### ISSUE TITLE
make the entry page be able to take a list of tags

### ISSUE THREAD

**Issue by readytheory** [regularstuff/tildeblog#9]
when entering a blog the data entry page should have a box for tags... you enter them with "," separators.

related to separate issue #10

I think urls should be like:    

"" or "/til" shows the list of pages
"/til/add" lets you create a new one.  
"/til/edit/#" lets you edit one, where "#" is the id of the one to edit

**Comment by regularstuff** [comment]
merged t9 dev 2024-03-11
